packageExtensions:
  "@craco/craco@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    peerDependencies:
      sass: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
